package models;
// Generated Dec 24, 2017 5:32:35 PM by Hibernate Tools 4.3.1


import play.data.validation.Constraints.*;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Coating generated by hbm2java
 */
public class Coating implements Serializable {

    private Integer id;
    private String code;
    @Required(message = "Title is not an optional.")
    @MinLength(value = 6, message = "Minimum length should be 6")
    private String title;
    private String description;
    private String imgPath;
    @Required(message = "Charge is not an optional.")
    private Double charge;
    private String remark;
    private boolean status;
    private Set<models.ProductHasCoating> productHasCoatings = new HashSet<>();

    public Coating() {
    }

    public Coating(boolean status) {
        this.status = status;
    }

    public Coating(String code, String title, String description, String imgPath, Double charge, String remark, boolean status, Set<models.ProductHasCoating> productHasCoatings) {
        this.code = code;
        this.title = title;
        this.description = description;
        this.imgPath = imgPath;
        this.charge = charge;
        this.remark = remark;
        this.status = status;
        this.productHasCoatings = productHasCoatings;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getImgPath() {
        return this.imgPath;
    }

    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

    public Double getCharge() {
        return this.charge;
    }

    public void setCharge(Double charge) {
        this.charge = charge;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    public Set<models.ProductHasCoating> getProductHasCoatings() {
        return this.productHasCoatings;
    }

    public void setProductHasCoatings(Set<models.ProductHasCoating> productHasCoatings) {
        this.productHasCoatings = productHasCoatings;
    }

}


