package models;
// Generated Jan 2, 2018 1:32:12 PM by Hibernate Tools 4.3.1


/**
 * DkcmsAbtUrl generated by hbm2java
 */
public class DkcmsAbtUrl implements java.io.Serializable {


    private Integer id;
    private DkcmsAbout dkcmsAbout;
    private String linkUrl;
    private String icon;
    private String textEn;
    private String textJp;
    private boolean status;

    public DkcmsAbtUrl() {
    }


    public DkcmsAbtUrl(DkcmsAbout dkcmsAbout, boolean status) {
        this.dkcmsAbout = dkcmsAbout;
        this.status = status;
    }

    public DkcmsAbtUrl(DkcmsAbout dkcmsAbout, String linkUrl, String icon, String textEn, String textJp, boolean status) {
        this.dkcmsAbout = dkcmsAbout;
        this.linkUrl = linkUrl;
        this.icon = icon;
        this.textEn = textEn;
        this.textJp = textJp;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public DkcmsAbout getDkcmsAbout() {
        return this.dkcmsAbout;
    }

    public void setDkcmsAbout(DkcmsAbout dkcmsAbout) {
        this.dkcmsAbout = dkcmsAbout;
    }

    public String getLinkUrl() {
        return this.linkUrl;
    }

    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl;
    }

    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getTextEn() {
        return textEn;
    }

    public void setTextEn(String textEn) {
        this.textEn = textEn;
    }

    public String getTextJp() {
        return textJp;
    }

    public void setTextJp(String textJp) {
        this.textJp = textJp;
    }

    public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }


}


