package models;
// Generated Jan 2, 2018 6:48:28 PM by Hibernate Tools 4.3.1



/**
 * DkcmsContact generated by hbm2java
 */
public class DkcmsContact  implements java.io.Serializable {


     private Integer id;
     private String mapLan;
     private String mapLon;
     private String informationEn;
     private String informationJp;
     private String addressEn;
     private String addressJp;
     private String contEmail;
     private String tel;
     private String website;
     private String submitMail;
     private String fbUrl;
     private String twitterUrl;
     private String googleplusUrl;
     private String insterUrl;

    public DkcmsContact() {
    }

    public DkcmsContact(String mapLan, String mapLon, String informationEn, String informationJp, String addressEn, String addressJp, String contEmail, String tel, String website, String submitMail, String fbUrl, String twitterUrl, String googleplusUrl, String insterUrl) {
       this.mapLan = mapLan;
       this.mapLon = mapLon;
       this.informationEn = informationEn;
       this.informationJp = informationJp;
       this.addressEn = addressEn;
       this.addressJp = addressJp;
       this.contEmail = contEmail;
       this.tel = tel;
       this.website = website;
       this.submitMail = submitMail;
       this.fbUrl = fbUrl;
       this.twitterUrl = twitterUrl;
       this.googleplusUrl = googleplusUrl;
       this.insterUrl = insterUrl;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMapLan() {
        return this.mapLan;
    }
    
    public void setMapLan(String mapLan) {
        this.mapLan = mapLan;
    }
    public String getMapLon() {
        return this.mapLon;
    }
    
    public void setMapLon(String mapLon) {
        this.mapLon = mapLon;
    }
    public String getInformationEn() {
        return this.informationEn;
    }
    
    public void setInformationEn(String informationEn) {
        this.informationEn = informationEn;
    }
    public String getInformationJp() {
        return this.informationJp;
    }
    
    public void setInformationJp(String informationJp) {
        this.informationJp = informationJp;
    }
    public String getAddressEn() {
        return this.addressEn;
    }
    
    public void setAddressEn(String addressEn) {
        this.addressEn = addressEn;
    }
    public String getAddressJp() {
        return this.addressJp;
    }
    
    public void setAddressJp(String addressJp) {
        this.addressJp = addressJp;
    }
    public String getContEmail() {
        return this.contEmail;
    }
    
    public void setContEmail(String contEmail) {
        this.contEmail = contEmail;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public String getSubmitMail() {
        return this.submitMail;
    }
    
    public void setSubmitMail(String submitMail) {
        this.submitMail = submitMail;
    }
    public String getFbUrl() {
        return this.fbUrl;
    }
    
    public void setFbUrl(String fbUrl) {
        this.fbUrl = fbUrl;
    }
    public String getTwitterUrl() {
        return this.twitterUrl;
    }
    
    public void setTwitterUrl(String twitterUrl) {
        this.twitterUrl = twitterUrl;
    }
    public String getGoogleplusUrl() {
        return this.googleplusUrl;
    }
    
    public void setGoogleplusUrl(String googleplusUrl) {
        this.googleplusUrl = googleplusUrl;
    }
    public String getInsterUrl() {
        return this.insterUrl;
    }
    
    public void setInsterUrl(String insterUrl) {
        this.insterUrl = insterUrl;
    }




}


