package models;
// Generated Jan 2, 2018 1:32:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DkcmsAbout generated by hbm2java
 */
public class DkcmsAbout implements java.io.Serializable {


    private Integer id;
    private String headingEn;
    private String descriptionEn;
    private String headingJp;
    private String descriptionJp;
    private String imgUrl;
    private Set<DkcmsAbtUrl> dkcmsAbtUrls = new HashSet<>();

    public DkcmsAbout() {
    }

    public DkcmsAbout(String headingEn, String descriptionEn, String headingJp, String descriptionJp, String imgUrl, Set<DkcmsAbtUrl> dkcmsAbtUrls) {
        this.headingEn = headingEn;
        this.descriptionEn = descriptionEn;
        this.headingJp = headingJp;
        this.descriptionJp = descriptionJp;
        this.imgUrl = imgUrl;
        this.dkcmsAbtUrls = dkcmsAbtUrls;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getHeadingEn() {
        return headingEn;
    }

    public void setHeadingEn(String headingEn) {
        this.headingEn = headingEn;
    }

    public String getDescriptionEn() {
        return descriptionEn;
    }

    public void setDescriptionEn(String descriptionEn) {
        this.descriptionEn = descriptionEn;
    }

    public String getHeadingJp() {
        return headingJp;
    }

    public void setHeadingJp(String headingJp) {
        this.headingJp = headingJp;
    }

    public String getDescriptionJp() {
        return descriptionJp;
    }

    public void setDescriptionJp(String descriptionJp) {
        this.descriptionJp = descriptionJp;
    }

    public String getImgUrl() {
        return this.imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public Set<DkcmsAbtUrl> getDkcmsAbtUrls() {
        return this.dkcmsAbtUrls;
    }

    public void setDkcmsAbtUrls(Set<DkcmsAbtUrl> dkcmsAbtUrls) {
        this.dkcmsAbtUrls = dkcmsAbtUrls;
    }


}


