package models;
// Generated Jan 2, 2018 1:32:12 PM by Hibernate Tools 4.3.1


/**
 * DkcmsSlider generated by hbm2java
 */
public class DkcmsSlider implements java.io.Serializable {


    private Integer id;
    private String titleEn;
    private String descriptionEn;
    private String titleJp;
    private String descriptionJp;
    private String btnUrl;
    private String imgUrl;
    private boolean status;

    public DkcmsSlider() {
    }

    public DkcmsSlider(boolean status) {
        this.status = status;
    }

    public DkcmsSlider(String titleEn, String descriptionEn, String titleJp, String descriptionJp, String btnUrl, String imgUrl, boolean status) {
        this.titleEn = titleEn;
        this.descriptionEn = descriptionEn;
        this.titleJp = titleJp;
        this.descriptionJp = descriptionJp;
        this.btnUrl = btnUrl;
        this.imgUrl = imgUrl;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitleEn() {
        return titleEn;
    }

    public void setTitleEn(String titleEn) {
        this.titleEn = titleEn;
    }

    public String getDescriptionEn() {
        return descriptionEn;
    }

    public void setDescriptionEn(String descriptionEn) {
        this.descriptionEn = descriptionEn;
    }

    public String getTitleJp() {
        return titleJp;
    }

    public void setTitleJp(String titleJp) {
        this.titleJp = titleJp;
    }

    public String getDescriptionJp() {
        return descriptionJp;
    }

    public void setDescriptionJp(String descriptionJp) {
        this.descriptionJp = descriptionJp;
    }

    public String getBtnUrl() {
        return this.btnUrl;
    }

    public void setBtnUrl(String btnUrl) {
        this.btnUrl = btnUrl;
    }

    public String getImgUrl() {
        return this.imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }


}


