package models;
// Generated Dec 24, 2017 5:32:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductHasSize generated by hbm2java
 */
public class ProductHasSize  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private Size size;
    private Set<Price> prices = new HashSet<>();

    public ProductHasSize() {
    }

    public ProductHasSize(Product product, Size size) {
       this.product = product;
       this.size = size;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Size getSize() {
        return this.size;
    }
    
    public void setSize(Size size) {
        this.size = size;
    }

    public Set<Price> getPrices() {
        return this.prices;
    }

    public void setPrices(Set<Price> prices) {
        this.prices = prices;
    }


}


